services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ceritificate:/etc/nginx/certs:ro
    networks:
      - hospital-queue-management-system_backend

networks:
  hospital-queue-management-system_backend:
    external: true
